[project]
name = "kvstore-mcp"
version = "0.1.0"
description = "MCP server for key-value store operations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "requests>=2.28.0",
    "python-dotenv>=1.0.0",
]
